# Generated by Django 4.0.5 on 2022-06-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pageCount',
            field=models.IntegerField(default=0),
        ),
    ]
