# Generated by Django 4.0.5 on 2022-06-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='posted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
