# Generated by Django 4.0.5 on 2022-06-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_review_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='book_id',
            field=models.IntegerField(default=1),
        ),
    ]
